.catalog:
  name: "nginx"
  version: "v1.0"
  description: "Nginx"
  questions:
    - variable: "NGINX_PORT"
      label: "nginx port"
      description: "i.e. 80"
      default: 80
      required: true
      type: "int"
nginx:
  scale: 1
